### ISSUE TITLE
Error in creating custom site definition in sharepoint 2016

### ISSUE THREAD

**Issue by SummiJ** [gdbd/sharepointcommon#2]
I am creating a custom site definition which I'll be using as a site template. I am able to create one with a list and some message on home page. I created one visual web part and added in default.aspx by registering it on default.aspx page.

<%@ Register Tagprefix="MyWebPartControls" Namespace="CustomSiteDefinition.LogonWebPart" Assembly="$SharePoint.Project.AssemblyFullName$" %>
<MyWebPartControls:LogonWebPart runat="server" />
        </div>

It is giving result as expected.

Now I want to add some default web parts like "Document Library" on home page. 

I am trying to edit in onet.xml.

![code](https://user-images.githubusercontent.com/17777765/34712622-7681ba84-f549-11e7-9616-caf343f64295.png)

As soon as I add above code I am getting following Error.

![error](https://user-images.githubusercontent.com/17777765/34712670-a3087430-f549-11e7-976e-fa2cc3f6ad36.png)

Find below stack trace.
[stack trace.txt](https://github.com/mikeedwards83/Glass.Mapper/files/1614455/stack.trace.txt)

Even if I try to add some custom web-part , I get these errors.

Any solution will be helpful :)

**Comment by gdbd** [comment]
Hi @SummiJ 
Please note that this error not correlates with sharepointCommon repository

Do you check ULS logs on time of this occured?
